src/main/java/org/jboss/as/quickstarts/entity/Message.java
package org.jboss.as.quickstarts.entity;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

@Entity
@NamedQueries({
        @NamedQuery(
                name = "Message.findAllByReceivingMember",
                query = "SELECT m from Message m WHERE m.recipient = :member ORDER BY m.timestamp DESC"
        ),
        @NamedQuery(
                name = "Message.findAllBySendingMember",
                query = "SELECT m from Message m WHERE m.sender = :member ORDER BY m.timestamp DESC"
        )
})
public class Message implements Serializable {

    @NotNull
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    @ManyToOne
    private Member recipient;

    @ManyToOne
    private Member sender;

    @NotNull
    private String message;

    @NotNull
    private Date timestamp;

    /**
     * Returns the Id
     * @return long
     */
    public long getId() {
        return this.id;
    }

    /**
     * Returns the recipient
     * @return Member
     */
    public Member getRecipient() {
        return this.recipient;
    }

    /**
     * Sets the recipient
     * @param member the Member to set as the recipient
     */
    public void setRecipient(Member member) {
        this.recipient = member;
    }

    /**
     * Returns the sender
     * @return Member
     */
    public Member getSender() {
        return this.sender;
    }

    /**
     * Sets the sender
     * @param member The Member to set as the sender
     */
    public void setSender(Member member) {
        this.sender = member;
    }

    /**
     * Returns the message
     * @return String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * Sets the message
     * @param message the message
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Sets the timestamp
     * @param timestamp the timestamp
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Returns the timestamp
     * @return Date
     */
    public Date getTimestamp() {
        return this.timestamp;
    }

    /**
     * Returns a humanly-readable representation of the timestamp
     * @return String
     */
    public String getReadableTimestamp() {
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy h:mm:ss a");
        return sdf.format(this.getTimestamp());
    }

    public String toString() {
        return String.format(
                "Message(Id: %d, Sender: %s, Recipient: %s, Message: %s, Timestamp: %s)",
                this.getId(),
                this.getSender(),
                this.getRecipient(),
                this.getMessage(),
                this.getReadableTimestamp()
        );
    }
}

src/main/java/org/jboss/as/quickstarts/controller/ChatController.java
package org.jboss.as.quickstarts.controller;

import org.jboss.as.quickstarts.entity.*;
import org.jboss.as.quickstarts.manager.MemberManager;
import org.jboss.as.quickstarts.manager.MessageManager;
import org.jboss.as.quickstarts.provider.MessageProvider;

import javax.annotation.Resource;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.jms.JMSContext;
import javax.jms.JMSDestinationDefinition;
import javax.jms.JMSDestinationDefinitions;
import javax.jms.Queue;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;

@JMSDestinationDefinitions(
        value = {
                @JMSDestinationDefinition(
                        name = "java:/queue/HELLOWORLDMDBQueue",
                        interfaceName = "javax.jms.Queue",
                        destinationName = "HelloWorldMDBQueue"
                ),
                @JMSDestinationDefinition(
                        name = "java:/topic/HELLOWORLDMDBTopic",
                        interfaceName = "javax.jms.Topic",
                        destinationName = "HelloWorldMDBTopic"
                )
        })
@Named("chatController")
@RequestScoped
public class ChatController implements Serializable {

    @Inject
    private JMSContext context;

    @Inject
    private MessageProvider messageProvider;

    @Inject
    private MemberManager memberManager;

    @Inject
    private MessageManager messageManager;

    @Resource(lookup = "java:/queue/HELLOWORLDMDBQueue")
    private Queue queue;

    private Member currentMember = (Member) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("member");

    private Member recipient = currentMember;

    /**
     * Returns the current Logged In Member
     * @return Member
     */
    public Member getCurrentMember() {
        return this.currentMember;
    }

    /**
     * Returns the Members that the current logged in member is allowed to see
     * @return List<Member>
     */
    public List<Member> getMembers() {
        return this.memberManager.findAllForMember(this.currentMember);
    }

    /**
     * Returns the current recipient
     * @return Member
     */
    public Member getRecipient() {
        return this.recipient;
    }

    /**
     * Sets the current recipient
     * @param member The member to be the recipient
     */
    public void setRecipient(Member member) {
        this.recipient = member;
    }

    /**
     * Returns the Messages that the currentMember has received
     * @return List<Message>
     */
    public List<Message> getReceivedMessages() {
        return this.messageManager.findByRecipient(this.currentMember);
    }

    /**
     * Returns the Messages that the currentMember has sent
     * @return List<Message>
     */
    public List<Message> getSentMessages() {
        return this.messageManager.findBySender(this.currentMember);
    }

    /**
     * Returns the Visibilities tha a Member can have
     * @return int[]
     */
    public int[] getVisibilities() {
        return Member.getVisibilities();
    }

    /**
     * Sends a Message
     * @throws IOException
     */
    public void doSend() throws IOException {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        String message = request.getParameter("chatForm:messageField");

        System.out.println(String.format("Sender: %s\nRecipient: %s\nMessage: %s",
                this.currentMember,
                this.recipient,
                message
        ));
        Message objectMessage = this.messageProvider.createFromSenderRecipientAndMessage(
                currentMember,
                this.recipient,
                message
        );

        this.context.createProducer().send(this.queue, objectMessage);

        this.redirect(request, "chat/index.jsf");
    }

    /**
     * Saves the currentMember - used when updating their visibility
     */
    public void doChangeVisibility() {
        this.memberManager.save(this.currentMember);
    }

    /**
     * Adds a Member to the Member's friends set
     * @param member the Member to become friends with
     */
    public void doAddFriend(Member member) {
        this.currentMember.addFriend(member);

        this.currentMember = this.memberManager.save(this.currentMember);
        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("member", this.currentMember);
    }

    /**
     * Removes a Member from the Member's friends set
     * @param member the Member to remove
     */
    public void doRemoveFriend(Member member) {
        this.currentMember.removeFriend(member);

        this.currentMember = this.memberManager.save(this.currentMember);
        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("member", this.currentMember);
    }

    /**
     * Redirects to a given location
     * @param request the current request
     * @param location the location to redirect to
     * @throws IOException
     */
    private void redirect(HttpServletRequest request, String location) throws IOException {
        HttpServletResponse response = (HttpServletResponse) FacesContext.getCurrentInstance().getExternalContext().getResponse();
        String contextPath = request.getContextPath();

        response.sendRedirect(String.format("%s/%s", contextPath, location));
    }
}

src/main/webapp/chat/create.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="/WEB-INF/templates/base.xhtml">
<ui:define name="content">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>Create Message</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h:form id="chatForm">
                <div class="form-group">
                    <h:outputLabel for="fromField">From</h:outputLabel>
                    <h:inputText id="fromField" styleClass="form-control" value="#{chatController.currentMember.username}" disabled="true"/>
                </div>
                <div class="form-group">
                    <h:outputLabel for="toField">To</h:outputLabel>
                    <h:selectOneRadio id="toField" value="#{chatController.recipient}" converter="#{memberConverter}" styleClass="table" required="true">
                        <f:selectItems value="#{chatController.members}" var="member" itemLabel="#{member.username}" itemValue="#{member}"/>
                    </h:selectOneRadio>
                </div>
                <div class="form-group">
                    <h:outputLabel for="messageField">Message</h:outputLabel>
                    <h:inputTextarea id="messageField" name="message" styleClass="form-control" required="true"/>
                </div>
                <h:commandButton id="send" value="Send" action="#{chatController.doSend}" styleClass="btn btn-default"/>
                <h:messages />
            </h:form>
        </div>
    </div>

</ui:define>
</ui:composition>

src/main/webapp/chat/friends.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/WEB-INF/templates/base.xhtml">
    <ui:define name="content">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1>Members</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <ui:repeat value="#{chatController.members}" var="member">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="col-sm-10">
                                <p><h:outputText value="#{member.username}" /></p>
                            </div>
                            <div class="col-sm-2">
                                <h:form>
                                    <ui:fragment rendered="#{chatController.currentMember.friends.contains(member)}">
                                        <h:commandButton action="#{chatController.doRemoveFriend(member)}" value="remove"/>
                                    </ui:fragment>
                                    <ui:fragment rendered="#{not chatController.currentMember.friends.contains(member)}">
                                        <h:commandButton action="#{chatController.doAddFriend(member)}" value="add"/>
                                    </ui:fragment>
                                </h:form>
                            </div>
                        </div>
                    </div>
                </ui:repeat>
            </div>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/chat/index.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/WEB-INF/templates/base.xhtml">
<ui:define name="content">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>Messages</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="col-md-12 text-center">
                <h2>Received Messages</h2>
            </div>
            <div class="col-md-12">
                <ui:repeat value="#{chatController.receivedMessages}" var="receivedMessage">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="col-md-12">
                                <p><h:outputText value="#{receivedMessage.message}" /></p>
                            </div>
                            <div class="col-md-12 text-right">
                                <p><small>from <h:outputText value="#{receivedMessage.sender.username} @ #{receivedMessage.readableTimestamp}" /></small></p>
                            </div>
                        </div>
                    </div>
                </ui:repeat>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12 text-center">
                <h2>Sent Messages</h2>
            </div>
            <div class="col-md-12">
                <ui:repeat value="#{chatController.sentMessages}" var="sentMessage">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="col-md-12">
                                <p><h:outputText value="#{sentMessage.message}" /></p>
                            </div>
                            <div class="col-md-12 text-right">
                                <p><small>to <h:outputText value="#{sentMessage.recipient.username} @ #{sentMessage.readableTimestamp}" /></small></p>
                            </div>
                        </div>
                    </div>
                </ui:repeat>
            </div>
        </div>

    </div>
</ui:define>
</ui:composition>

src/main/webapp/chat/visibility.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="/WEB-INF/templates/base.xhtml">
    <ui:define name="content">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1>Set Visibility</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h:form id="visibilityForm">
                    <div class="form-group">
                        <h:outputLabel for="visibilityField">Visibility</h:outputLabel>
                        <h:selectOneRadio id="visibilityField" value="#{chatController.currentMember.visibility}" styleClass="table">
                            <f:selectItems value="#{chatController.visibilities}" var="visibility" itemLabel="#{visibility}" itemValue="#{visibility}"/>
                        </h:selectOneRadio>
                    </div>
                    <h:commandButton id="send" value="Save" action="#{chatController.doChangeVisibility}" styleClass="btn btn-default"/>
                    <h:messages />
                </h:form>
            </div>
        </div>
    </ui:define>
</ui:composition>